apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-app
  namespace: argocd
spec:
  project: default

  source:
    repoURL: git@github.com:GCLIM/test-app.git
    targetRevision: main
    path: dev
  destination:
    server: https://kubernetes.default.svc
    namespace: test-app-namespace

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true